/**
 * shared/ui Public API — 앱 전역에서 쓰는 "범용 UI 부품" 단일 창구.
 *
 * 두 출처를 하나로 합쳐 노출한다:
 *  1) bo-ui-kit (npm) — 디자인 시스템이 제공하는 컴포넌트 전체 (re-export)
 *  2) app-shared      — 킷에 없어 앱에서 같은 토큰으로 만든 프리미티브(Card·Table)
 *
 * 상위 레이어는 출처를 신경 쓰지 않고 `@/shared/ui` 한 곳에서만 가져온다.
 * (캡슐화 — 킷에 Card/Table 이 추가되면 아래 app-shared 줄만 킷 re-export 로 바꾸면 됨)
 */

// 1) 킷 컴포넌트 전체 re-export (bo-ui-kit@0.2.0)
export {
  Button,
  buttonVariants,
  Checkbox,
  Input,
  inputVariants,
  Label,
  Field,
  InputOTP,
  InputOTPSlot,
  InputOTPSeparator,
  Meter,
  Toggle,
  toggleVariants,
  ToggleGroup,
  ToggleGroupItem,
  Select,
  Switch,
  switchVariants,
  Separator,
  Skeleton,
  Spinner,
  spinnerVariants,
  Textarea,
  Avatar,
  avatarVariants,
  AvatarGroup,
  Badge,
  badgeVariants,
  NumberField,
  RadioGroup,
  RadioGroupItem,
  SegmentedControl,
  Tabs,
  TabsList,
  TabsTrigger,
  TabsContent,
  Accordion,
  AccordionItem,
  Collapsible,
  Breadcrumb,
  Alert,
  Toast,
  Tooltip,
  ScrollArea,
  Dialog,
  DialogTrigger,
  DialogContent,
  DialogHeader,
  DialogBody,
  DialogTitle,
  DialogDescription,
  DialogFooter,
  DialogClose,
  AlertDialog,
  Sheet,
  SheetTrigger,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetDescription,
  SheetFooter,
  SheetClose,
  Drawer,
  DrawerHeader,
  DrawerTitle,
  DrawerDescription,
  DrawerFooter,
} from "bo-ui-kit";
export type {
  ButtonProps,
  CheckboxProps,
  InputProps,
  LabelProps,
  FieldProps,
  InputOTPProps,
  MeterProps,
  ToggleProps,
  ToggleGroupProps,
  SelectProps,
  SelectOption,
  SwitchProps,
  SeparatorProps,
  SkeletonProps,
  SpinnerProps,
  TextareaProps,
  AvatarProps,
  AvatarGroupProps,
  BadgeProps,
  NumberFieldProps,
  RadioGroupProps,
  SegmentedControlProps,
  SegmentedOption,
  TabsProps,
  AccordionProps,
  CollapsibleProps,
  BreadcrumbProps,
  BreadcrumbItemData,
  AlertProps,
  ToastProps,
  TooltipProps,
  DialogProps,
  AlertDialogProps,
  SheetProps,
  DrawerProps,
} from "bo-ui-kit";

// 2) app-shared 프리미티브 (킷에 없는 Card·Table)
export {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter,
} from "./card";
export {
  Table,
  TableHeader,
  TableBody,
  TableRow,
  TableHead,
  TableCell,
} from "./table";
export { ConfirmDialog, type ConfirmDialogProps } from "./confirm-dialog";
export * from "./icons";
