import type { PgTransaction } from "./types";

/**
 * 거래내역 시드 — 구 BO `/admin/transaction/listData` 실제 응답 샘플 1건 +
 * 표/필터가 의미 있게 보이도록 상태·결제수단·통화·국가를 다양화한 데모 데이터.
 * 실서버 연결 시 이 시드는 사용되지 않는다(api 레이어가 실제 응답으로 대체).
 */
export const PG_TRANSACTION_SEED: PgTransaction[] = [
  {
    rownum: 1,
    transactId: "260709100436GZ00VmK8",
    transactDate: "2026-07-09 10:04:40",
    merchantId: "t_USD_Test",
    merchantName: "USD_TEST_MERCHANT",
    hostingName: "페이버스테스트",
    transactOrderId: "testOrder_34331n6a18",
    transactTypeName: "SALE",
    transactStatusName: "PENDING",
    transactProcessCurrency: "USD",
    transactProcessAmount: 1,
    transactSchemeName: "PayPal",
    transactCardNo: "",
    transactCardHolder: null,
    methodDisplayName: "Mobile Wallet",
    transactRequestCurrency: "USD",
    transactRequestAmount: 1,
    partnerTid: null,
    customerId: "sjjo01_1rue1p1t3k",
    transCountryCd: "GO",
    transCountryNm: "Global",
  },
  {
    rownum: 2,
    transactId: "260709101210AB01XqL2",
    transactDate: "2026-07-09 10:12:10",
    merchantId: "m_KRW_Shop",
    merchantName: "KR_FASHION_STORE",
    hostingName: "페이버스코리아",
    transactOrderId: "ord_krw_88213",
    transactTypeName: "SALE",
    transactStatusName: "SUCCESS",
    transactProcessCurrency: "KRW",
    transactProcessAmount: 49000,
    transactSchemeName: "Visa",
    transactCardNo: "465812******1234",
    transactCardHolder: "HONG GILDONG",
    methodDisplayName: "Credit Card",
    transactRequestCurrency: "KRW",
    transactRequestAmount: 49000,
    partnerTid: "PTID-KR-0021",
    customerId: "hong_9a2b",
    transCountryCd: "KR",
    transCountryNm: "Korea",
  },
  {
    rownum: 3,
    transactId: "260709102955CD02ZmN7",
    transactDate: "2026-07-09 10:29:55",
    merchantId: "m_JPY_Game",
    merchantName: "JP_GAME_TOPUP",
    hostingName: "페이버스재팬",
    transactOrderId: "jp_topup_5521",
    transactTypeName: "SALE",
    transactStatusName: "SUCCESS",
    transactProcessCurrency: "JPY",
    transactProcessAmount: 3000,
    transactSchemeName: "Master",
    transactCardNo: "512345******9987",
    transactCardHolder: "SATO TARO",
    methodDisplayName: "Credit Card",
    transactRequestCurrency: "JPY",
    transactRequestAmount: 3000,
    partnerTid: "PTID-JP-7742",
    customerId: "sato_x91",
    transCountryCd: "JP",
    transCountryNm: "Japan",
  },
  {
    rownum: 4,
    transactId: "260709104410EF03PpQ1",
    transactDate: "2026-07-09 10:44:10",
    merchantId: "t_USD_Test",
    merchantName: "USD_TEST_MERCHANT",
    hostingName: "페이버스테스트",
    transactOrderId: "testOrder_77120x2",
    transactTypeName: "SALE",
    transactStatusName: "FAILED",
    transactProcessCurrency: "USD",
    transactProcessAmount: 25,
    transactSchemeName: "PayPal",
    transactCardNo: "",
    transactCardHolder: null,
    methodDisplayName: "Mobile Wallet",
    transactRequestCurrency: "USD",
    transactRequestAmount: 25,
    partnerTid: null,
    customerId: "guest_kk29",
    transCountryCd: "GO",
    transCountryNm: "Global",
  },
  {
    rownum: 5,
    transactId: "260709110002GH04RrS9",
    transactDate: "2026-07-09 11:00:02",
    merchantId: "m_EUR_Travel",
    merchantName: "EU_TRAVEL_AGENCY",
    hostingName: "페이버스유럽",
    transactOrderId: "eu_trv_30014",
    transactTypeName: "SALE",
    transactStatusName: "SUCCESS",
    transactProcessCurrency: "EUR",
    transactProcessAmount: 120,
    transactSchemeName: "Visa",
    transactCardNo: "401288******5590",
    transactCardHolder: "MARIE CURIE",
    methodDisplayName: "Credit Card",
    transactRequestCurrency: "EUR",
    transactRequestAmount: 120,
    partnerTid: "PTID-EU-1180",
    customerId: "marie_3f",
    transCountryCd: "FR",
    transCountryNm: "France",
  },
  {
    rownum: 6,
    transactId: "260709111530IJ05TtU4",
    transactDate: "2026-07-09 11:15:30",
    merchantId: "m_KRW_Shop",
    merchantName: "KR_FASHION_STORE",
    hostingName: "페이버스코리아",
    transactOrderId: "ord_krw_88245",
    transactTypeName: "REFUND",
    transactStatusName: "SUCCESS",
    transactProcessCurrency: "KRW",
    transactProcessAmount: 49000,
    transactSchemeName: "Visa",
    transactCardNo: "465812******1234",
    transactCardHolder: "HONG GILDONG",
    methodDisplayName: "Credit Card",
    transactRequestCurrency: "KRW",
    transactRequestAmount: 49000,
    partnerTid: "PTID-KR-0021",
    customerId: "hong_9a2b",
    transCountryCd: "KR",
    transCountryNm: "Korea",
  },
  {
    rownum: 7,
    transactId: "260709112845KL06VvW6",
    transactDate: "2026-07-09 11:28:45",
    merchantId: "m_USD_SaaS",
    merchantName: "US_SAAS_BILLING",
    hostingName: "페이버스US",
    transactOrderId: "saas_sub_9910",
    transactTypeName: "SALE",
    transactStatusName: "PENDING",
    transactProcessCurrency: "USD",
    transactProcessAmount: 99,
    transactSchemeName: "AMEX",
    transactCardNo: "371449******0005",
    transactCardHolder: "JOHN SMITH",
    methodDisplayName: "Credit Card",
    transactRequestCurrency: "USD",
    transactRequestAmount: 99,
    partnerTid: "PTID-US-4410",
    customerId: "jsmith_a1",
    transCountryCd: "US",
    transCountryNm: "United States",
  },
  {
    rownum: 8,
    transactId: "260709113310MN07XxY0",
    transactDate: "2026-07-09 11:33:10",
    merchantId: "m_CNY_Mall",
    merchantName: "CN_ONLINE_MALL",
    hostingName: "페이버스차이나",
    transactOrderId: "cn_mall_20881",
    transactTypeName: "SALE",
    transactStatusName: "CANCELLED",
    transactProcessCurrency: "CNY",
    transactProcessAmount: 350,
    transactSchemeName: "UnionPay",
    transactCardNo: "622202******7788",
    transactCardHolder: "WANG WEI",
    methodDisplayName: "Credit Card",
    transactRequestCurrency: "CNY",
    transactRequestAmount: 350,
    partnerTid: "PTID-CN-9021",
    customerId: "wangw_77",
    transCountryCd: "CN",
    transCountryNm: "China",
  },
  {
    rownum: 9,
    transactId: "260709114725OP08ZzA3",
    transactDate: "2026-07-09 11:47:25",
    merchantId: "t_USD_Test",
    merchantName: "USD_TEST_MERCHANT",
    hostingName: "페이버스테스트",
    transactOrderId: "testOrder_55102m9",
    transactTypeName: "SALE",
    transactStatusName: "SUCCESS",
    transactProcessCurrency: "USD",
    transactProcessAmount: 5,
    transactSchemeName: "PayPal",
    transactCardNo: "",
    transactCardHolder: null,
    methodDisplayName: "Mobile Wallet",
    transactRequestCurrency: "USD",
    transactRequestAmount: 5,
    partnerTid: null,
    customerId: "sjjo01_1rue1p1t3k",
    transCountryCd: "GO",
    transCountryNm: "Global",
  },
  {
    rownum: 10,
    transactId: "260709120118QR09BbC5",
    transactDate: "2026-07-09 12:01:18",
    merchantId: "m_GBP_Sub",
    merchantName: "UK_STREAMING",
    hostingName: "페이버스UK",
    transactOrderId: "uk_stream_4412",
    transactTypeName: "SALE",
    transactStatusName: "SUCCESS",
    transactProcessCurrency: "GBP",
    transactProcessAmount: 12,
    transactSchemeName: "Master",
    transactCardNo: "555544******3321",
    transactCardHolder: "EMMA WATSON",
    methodDisplayName: "Credit Card",
    transactRequestCurrency: "GBP",
    transactRequestAmount: 12,
    partnerTid: "PTID-UK-2205",
    customerId: "emma_ws",
    transCountryCd: "GB",
    transCountryNm: "United Kingdom",
  },
  {
    rownum: 11,
    transactId: "260709121944ST10DdE8",
    transactDate: "2026-07-09 12:19:44",
    merchantId: "m_JPY_Game",
    merchantName: "JP_GAME_TOPUP",
    hostingName: "페이버스재팬",
    transactOrderId: "jp_topup_5602",
    transactTypeName: "SALE",
    transactStatusName: "FAILED",
    transactProcessCurrency: "JPY",
    transactProcessAmount: 5000,
    transactSchemeName: "JCB",
    transactCardNo: "353011******4410",
    transactCardHolder: "SUZUKI HANA",
    methodDisplayName: "Credit Card",
    transactRequestCurrency: "JPY",
    transactRequestAmount: 5000,
    partnerTid: "PTID-JP-7799",
    customerId: "suzuki_h3",
    transCountryCd: "JP",
    transCountryNm: "Japan",
  },
  {
    rownum: 12,
    transactId: "260709123050UV11FfG2",
    transactDate: "2026-07-09 12:30:50",
    merchantId: "m_USD_SaaS",
    merchantName: "US_SAAS_BILLING",
    hostingName: "페이버스US",
    transactOrderId: "saas_sub_9925",
    transactTypeName: "SALE",
    transactStatusName: "SUCCESS",
    transactProcessCurrency: "USD",
    transactProcessAmount: 199,
    transactSchemeName: "Visa",
    transactCardNo: "424242******4242",
    transactCardHolder: "ALICE PARK",
    methodDisplayName: "Credit Card",
    transactRequestCurrency: "USD",
    transactRequestAmount: 199,
    partnerTid: "PTID-US-4433",
    customerId: "alice_pk",
    transCountryCd: "US",
    transCountryNm: "United States",
  },
];
